apiVersion: v1
kind: ConfigMap
metadata:
  name: agents-config
  namespace: synapse
data:
  EMBEDDING_MODEL: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
  REASONING_MODEL: "gemini-2.5-flash"
  FAST_MODEL: "gemini-2.5-flash"
  SYNAPSE_API_URL: "http://backend-svc:5000"
