apiVersion: v1
kind: Service
metadata:
  name: agents-svc
  namespace: synapse
  labels:
    app: agents
spec:
  type: ClusterIP
  selector:
    app: agents
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
