apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: synapse

resources:
  - namespace.yaml
  - agents-configmap.yaml
  - agents-secret.yaml
  - agents-deployment.yaml
  - agents-service.yaml
  - agents-hpa.yaml
  - backend-secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
