using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using BusinessModel = Synapse.Core.Models.Business.Business;
using Synapse.Core.Models.Invoice;

namespace Synapse.Core.Services.Invoice;

public interface IEuInvoicePdfService
{
    Task<byte[]> GeneratePdfAsync(KsefInvoice invoice, BusinessModel business, CancellationToken ct = default);
}

public class EuInvoicePdfService : IEuInvoicePdfService
{
    public Task<byte[]> GeneratePdfAsync(KsefInvoice invoice, BusinessModel business, CancellationToken ct)
    {
        var invoiceNumber = $"SYN-{invoice.Id.ToString()[..8].ToUpper()}-{invoice.PeriodStart:yyyyMM}";
        var net = invoice.TotalAmountCents / 100m;
        var vatAmount = Math.Round(net * invoice.VatRatePct, 2);
        var gross = net + vatAmount;
        var vatPct = (int)Math.Round(invoice.VatRatePct * 100);

        var pdf = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(t => t.FontSize(10));

                page.Header().Column(col =>
                {
                    col.Item().Text("VAT INVOICE").FontSize(20).Bold();
                    col.Item().Text(invoiceNumber).FontSize(12).FontColor(Colors.Grey.Medium);
                });

                page.Content().PaddingVertical(10).Column(col =>
                {
                    col.Spacing(8);

                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Column(inner =>
                        {
                            inner.Item().Text("SELLER").Bold();
                            inner.Item().Text("Synapse LifeQuest Sp. z o.o.");
                            inner.Item().Text("ul. Platformowa 1, 30-001 Kraków");
                            inner.Item().Text("NIP: PL0000000000");
                        });

                        row.RelativeItem().Column(inner =>
                        {
                            inner.Item().Text("BUYER").Bold();
                            inner.Item().Text(business.Name);
                            inner.Item().Text(business.Address);
                            if (business.City is not null)
                                inner.Item().Text(business.City);
                        });
                    });

                    col.Item().LineHorizontal(0.5f);

                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Text($"Period: {invoice.PeriodStart:yyyy-MM-dd} – {invoice.PeriodEnd:yyyy-MM-dd}");
                        row.RelativeItem().AlignRight().Text($"Date: {invoice.CreatedAt:yyyy-MM-dd}");
                    });

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.RelativeColumn(4);
                            cols.RelativeColumn();
                            cols.RelativeColumn();
                            cols.RelativeColumn();
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Description").Bold();
                            header.Cell().AlignRight().Text("Net").Bold();
                            header.Cell().AlignRight().Text($"VAT {vatPct}%").Bold();
                            header.Cell().AlignRight().Text("Gross").Bold();
                        });

                        table.Cell().Text($"Platform commission — {invoice.MissionCount} completed mission(s)");
                        table.Cell().AlignRight().Text($"{net:F2}");
                        table.Cell().AlignRight().Text($"{vatAmount:F2}");
                        table.Cell().AlignRight().Text($"{gross:F2}");
                    });

                    col.Item().LineHorizontal(0.5f);

                    col.Item().AlignRight().Text($"TOTAL DUE: {gross:F2} EUR").Bold().FontSize(12);
                });

                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by Synapse Platform — ");
                    t.Span($"{DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
                });
            });
        });

        return Task.FromResult(pdf.GeneratePdf());
    }
}
